version: '3.8'

services:
  api_service:
    build: .
    command: bash -c "pip install --upgrade pip && pip install poetry && poetry config virtualenvs.create false && poetry install --no-root && poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app
    ports:
      - 5000:8000
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: favorites_db

  postgres:
    image: postgres:15-alpine
    container_name: favorite_api
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: favorites_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d favorites_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
  redis_data:
